import numpy as np
from matplotlib import pyplot as plt
Rastrigin_ga_result = np.load('Rastrigin_ga.npy')
Rastrigin_ccga_result = np.load('Rastrigin_ccga.npy')
Griewank_ga_result = np.load('Griewank_ga.npy')
Griewank_ccga_result = np.load('Griewank_ccga.npy')
Schewefel_ga_result = np.load('Schewefel_ga.npy')
Schewefel_ccga_result = np.load('Schewefel_ccga.npy')
Ackley_ga_result = np.load('Ackley_ga.npy')
Ackley_ccga_result = np.load('Ackley_ccga.npy')

# fig, ax = plt.subplots(2,2)
# print(np.unique(Rastrigin_ga_result))
# print(np.unique(Rastrigin_ccga_result))
# ax[0][0].plot(range(len(Rastrigin_ga_result)), Rastrigin_ga_result)
# ax[0][0].plot(range(len(Rastrigin_ccga_result)), Rastrigin_ccga_result)
# ax[0][0].set_ylim(0, 40)
# ax[1][0].plot(range(len(Griewank_ga_result)), Griewank_ga_result)
# ax[1][0].plot(range(len(Griewank_ccga_result)), Griewank_ccga_result)
# ax[1][0].set_ylim(0, 8)
# ax[0][1].plot(range(len(Schewefel_ga_result)), Schewefel_ga_result)
# ax[0][1].plot(range(len(Schewefel_ccga_result)), Schewefel_ccga_result)
# ax[0][1].set_ylim(0, 400)
# ax[1][1].plot(range(len(Ackley_ga_result)), Ackley_ga_result)
# ax[1][1].plot(range(len(Ackley_ccga_result)), Ackley_ccga_result)
# ax[1][1].set_ylim(0, 16)
# plt.show()


fig, ax = plt.subplots(figsize=(8, 6))
ax.plot(range(len(Ackley_ga_result)), Ackley_ga_result, label='standard_ga')
ax.plot(range(len(Ackley_ccga_result)), Ackley_ccga_result, label='ccga')
ax.set_xlabel('function evaluations')
ax.set_ylabel('best individual')
ax.set_ylim(0, 16)
ax.set_title('Ackley function')
plt.grid()
plt.legend()
plt.savefig('Ackeley function')